### ISSUE TITLE
Remove const modifier from enum

### ISSUE THREAD

**Issue by Exulansis** [jolocom/vaulted-key-provider#1]
Unless there's a good reason to keep it, this should be removed to avoid some limitations this brings.

https://github.com/jolocom/vaulted-key-provider/blob/facdd79e52da06cc4d919b6986656b0061ea1d45/src/types.ts#L12

**Comment by chunningham** [comment]
fixed in [495c28b](https://github.com/jolocom/vaulted-key-provider/commit/495c28b65a7ee1fdfe94e4ba874fe110027dcac6)
